<?php
/**
 * Created by PhpStorm.
 * User: twitf
 * Date: 2018/1/5
 * Time: 17:48
 */
namespace twitf\dropzone;
use yii\helpers\ArrayHelper;
use Yii;
class RemoveAction extends \yii\base\Action{
    public $config = [];
    public $savePath = '';
    public function init()
    {
        $_config['fileRoot'] = Yii::getAlias('@webroot');
        $this->config = ArrayHelper::merge($_config, $this->config);
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run(){
        $post=Yii::$app->request->post();
        @unlink($this->config['fileRoot'].$post['url']);
        $filedir  = dirname($post['url']);
        $files = @scandir($this->config['fileRoot'].$filedir);
        if (count($files)<=2) {
            @rmdir($this->config['fileRoot'].$filedir);//如果是./和../,直接删除文件夹
        }
        Yii::$app->response->format=yii\web\Response::FORMAT_JSON;
        return ['status'=>'success'];
    }
}